export const title = "Wolf's Superior Sandwiches"

export const hours = {
  "Monday": [11, 22],
  "Tuesday": [11, 22],
  "Wednesday": [11, 22],
  "Thursday": [11, 22],
  "Friday": [11, 23],
  "Saturday": [11, 23],
  "Sunday": [11, 21],
}

export const contact = {
  "phone": "484-487-3970",
  "address": {
    "street": "4417 Pennell Rd.",
    "city": "Aston",
    "state": "Pennsylvania",
    "postal": "19014",
  },
}

export const menu = [
  {
    "name": "The Ashley",
    "description": "panko breaded mozzarella, roma tomatoes, basil aioli, arugula, balsamic reduction",
    "price": 9,
    "category": ["Specialty Sandwiches"],
    "tags": ["SR"],
  },
  {
    "name": "Pollo Loco",
    "description": "pulled chicken, chimichurri, cheddar, jalapenos, pickled onions, cilantro",
    "price": 9,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF"],
  },
  {
    "name": "The Pacino",
    "description": "grilled chicken breast, hot pepper spread, long hots, roasted Roma tomatoes, basil aioli, arugula, mozzarella and red pepper flakes",
    "price": 9.5,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF"],
  },
  {
    "name": "The De Niro",
    "description": "chicken cutlet, roasted peppers, prosciutto di Parma, pesto mayo, arugula, red onion, Aged provolone, balsamic reduction",
    "price": 9.5,
    "category": ["Specialty Sandwiches"],
    "tags": ["SR"],
  },
  {
    "name": "The Liotta",
    "description": "Italian sausage, peppers, onions, roasted garlic aioli and fresh mozzarella, oven toasted",
    "price": 9.5,
    "category": ["Specialty Sandwiches"],
    "tags": ["SR", "GF"],
  },
  {
    "name": "The Pesci",
    "description": "prosciutto di parma, sopressata, hot capicola, Genoa salami, sliced Roma tomatoes, red onion, aged sharp provolone, red wine vinegar, olive oil, red pepper flakes",
    "price": 9.5,
    "category": ["Specialty Sandwiches"],
    "tags": [],
  },
  {
    "name": "The Pickle Rick",
    "description": "bourbon bbq brisket, fried pickles, cooper sharp, garlic aioli",
    "price": 9.5,
    "category": ["Specialty Sandwiches"],
    "tags": ["SR", "GF"],
  },
  {
    "name": "Death By Swine",
    "description": "bourbon bbq pork belly, cheddar cheese, pulled pork, smoked gouda cheese sauce, chipotle ranch, spicy pickles, bacon, onion rings and 2 sunny up eggs ",
    "price": 10.5,
    "category": ["Specialty Sandwiches"],
    "tags": ["SR", "GF"],
  },
  {
    "name": "The So-Cal",
    "description": "turkey, bacon, avocado, tomato, arugula, mayo, smoked cheddar",
    "price": 9,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF"],
  },
  {
    "name": "The Big Memphis",
    "description": "bbq brisket, smoked gouda mac n chez, jalapenos, onion rings, bourbon bbq sauce",
    "price": 9.5,
    "category": ["Specialty Sandwiches"],
    "tags": [],
  },
  {
    "name": "The NOLA",
    "description": "Andouille sausage, creole mayo, pickles, red onion",
    "price": 9,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF"],
  },
  {
    "name": "The Chi-Town Beef",
    "description": "sliced beef, giardiniera (assorted pickled vegetables and chilies) beef jus and provolone",
    "price": 9,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF", "SR"],
  },
  {
    "name": "The Backyard BBQ",
    "description": "buttermilk fried chicken tenders, iceberg lettuce, sliced tomato, black pepper pork belly, avocado and deviled egg mayo",
    "price": 9.5,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF"],
  },
  {
    "name": "The Cozumel",
    "description": "citrus braised pork, salsa verde, salsa roja, red onion, queso fresco, cilantro",
    "price": 9,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF"],
  },
  {
    "name": "The Corey Matthew's",
    "description": "ham, cooper sharp, iceberg lettuce, tomato, yellow mustard, potato chips",
    "price": 8.5,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF"],
  },
  {
    "name": "The Nor-Cal",
    "description": "roast beef, artichoke bruschetta, roasted garlic mayo, swiss, roma tomatoes, red onion, fresh basil",
    "price": 9,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF"],
  },
  {
    "name": "The Big Cubano",
    "description": "sliced ham, pulled pork, bacon, salami, swiss, mustard, lettuce, tomato",
    "price": 10,
    "category": ["Specialty Sandwiches"],
    "tags": ["GF"],
  },
  {
    "name": "The Thanksgiving Jawn",
    "description": "sliced Turkey, stuffing, cranberry, mayo",
    "price": 9.5,
    "category": ["Specialty Sandwiches"],
    "tags": [],
  },
  {
    "name": "The Gritty",
    "description": "a mix of chopped steak and habbersett scrapple, caramelized onions, spicy ketchup, creamy cheese sauce",
    "price": 9,
    "category": ["Specialty Sandwiches"],
    "tags": [],
  },
]
